window.STUDENTS_LIST_DATA = `CHIENO JAY BATON
MARK JAY BATON
RENAN BULAMBOT
ADRIAN DAYANGGA
ALEXANDER DIALANG
JESRYLLE LANUBAY
HANES MALID
BEE JAY MALIG-ON
JOSHUA MALNGAN
OWEN GAEL MARQUEZ
REINIER JAZZ MENDEZ
MARK ANTHONY PENDATON
ALEXIS JAMES PIANG
JOHNRICKS SAGO
CARLOS JR TAN
IVAN YATA
ANGELA BARRINA
KEITHLYN BATERNA
RHEA BATON
ZIA BATON
CHRISANTHA BINUHAY
FRIELYN CAPION
CHERRY CAWADI
MAE DABLEO
HANNA MAE DIZON
ANDREA LESIONAN
SHANA ROSE MALASUGUE
JESSICA MAMON
HONNEYBIE MANTE
ALPHA MARIANO
NORLEAH NUFABLE
HANDRIA PABLO
RENALI JANE PIANG
ROVELYN PIANG
CRISTAL APPLE PLATEROS
AURILLA RELACION
ANDREA REPA
PRISCILLA GREEZEL SAN
RITCHELLE TUNGON
ANGELEN UBAUB
RACHELLE WALOK
JELYN YUAG
GRADE8 STUDENT`;
