window.STUDENTS_LIST_DATA = `ALMAR ALON
MARK ANDREAN BATON
ZIAN BATON
ROGIE PAUL CAWADE
CHORIMARK CUYOG
PRINCE JOEBERT DEDURO
RECHIE FAVILA
IDAN JAMES GADIALE
JOSHUA GAMBULAN
EROSE MALID
KING MATT ORLAN MANIB
RUSSEL JAMES PANALIGAN
PIT TROY PENDEZ
JEMUEL REPAJA
FRANZ CHESTER SAGO
RAL JAY TAMGLANG
CHRISTINE ALCONERA
PRECIOUS GWEN NEPOMOCENO
SHELLA MAE PALABASAN
JENEVIVE TOL
GLORY JANE YATA
GRADE9 STUDENT`;
