window.STUDENTS_LIST_DATA = `AJ BALUNTO
VINCE MARI JOHN GADIALE
JUS LESIONAN
MARK ANTHONY LIBOSADA
CHRYSLER JUDE MALIG-ON
DANIEL MALUMPONG
GERALD MATOS
ROGELIO JR PENDATUN
KIER LAWRENCE QUIÑONES
RICHARD JR SOY
GABRIEL YATA
NORAMIE CAPAWAN
GRETCHEN GEA CAWADI
JHILLIAN MAE CAWADI
PRINCESS TWELVE COYOCA
EUNYSE DIAZ
RONA MAE JUAN
RHEALYN MAGALID
KRISHA MAE MAGLUYAN
RHEA MAE PANGILAN
WINDY GLAZE TUNGON
HANNAH JEAN VELASCO
CHERO QUE CAWADE
VINCENT RELON CAWADE
ALEX JEPOY CAWADI
KEM JOHN GUINANG
ADRIANE CARL MALADIANON
XIAN MALNGAN
RALPH EDWARD PADAYHAG
MARK JAY PARASAN
RICHAELL SALAWA
PRINCE NIETHAN TRAVIS SANICO
REYNALDO UBAUB
CATRINA BATON
PATRICIA JOY CAWADI
JEANINE FLORES
SANDARA GANSING
MARIELA LIBRADO
SHAINA MAE MALID
SOPHIA BIANCA MALID
MARY JOY RAMITAN
FRANCIS GRACE SALILA
DAISY TAKUYAN
NORBIE SHANE TOL
GRADE7 STUDENT`;
